/**:
  ros__parameters:
    # ─────────── Temps simulé ──────────────────────
    use_sim_time: true        # indispensable avec ros2 bag play --clock
    if_lidar_only: true       # pas d’IMU, on traite seulement le LiDAR

    # ─────────── LiDARs ────────────────────────────
    lidars: ["Airy96"]

    # ─── Paramètres spécifiques à Airy96 ───────────
    Airy96:
      topic_lidar: "/rslidar_points"
      lidar_type: "Airy96"
      scan_line: 96
      blind: 0.5
      q_lb: [1.0, 0.0, 0.0, 0.0]
      t_lb: [0.0, 0.0, 0.0]
      w_pt: 0.01
      # … autres clés si besoin …
      fov_up: 90.0
      fov_down: 0.0
      rotation_rate: 10.0
      resolution_h: 0.4
      resolution_v: 0.947
      lidar_time_offset: 0.0   # offset global en secondes

    # ─── Paramètres généraux de RESPLE ─────────────
    knot_hz: 100
    ds_scan_voxel: 0.5
    point_filter_num: 3
    nn_thresh: 0.5
    coeff_cov: 3.0
    num_nn: 8

    # ─── Extraction de landmarks ───────────────────
    ds_lm_voxel: 0.5         # <— CE PARAM manquant !
    cube_len: 1000.0

    # ─── Covariances & bruits ─────────────────────
    cov_P0: 0.02
    cov_RCP_pos_old: 0.1
    cov_RCP_ort_old: 0.1
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.2
    std_sys_ort: 0.1
    cov_acc: [1.0, 1.0, 1.0]
    cov_gyro: [0.1, 0.1, 0.1]
    cov_ba:   [0.2, 0.2, 0.2]
    cov_bg:   [0.2, 0.2, 0.2]

    # ─── Itérations & MAJ ─────────────────────────
    n_iter: 1
    num_points_upd: 500
