/**:
  ros__parameters:
    topic_imu: /livox/imu
    acc_ratio: true # if true, multiply accelerometer measurements with g
    lidars: ["livox"]
    livox:
      topic_lidar: /livox/lidar 
      lidar_type: AviaResple
      scan_line: 4
      blind: 2.0
      q_lb: [1.0, 0.0, 0.0, 0.0]        
      t_lb: [-0.04165, -0.02326, 0.0284]
      w_pt: 0.01
    lidar_time_offset: 0.0  # time offset between lidar and IMU, unit: s
    
    knot_hz: 100
    if_lidar_only: true # if true, use LiDAR-only odometry
    
    ds_scan_voxel: 0.5
    point_filter_num: 1
    nn_thresh: 0.5
    coeff_cov: 5.0
    num_nn: 5

    ds_lm_voxel: 0.5
    cube_len: 1000.0

    cov_P0: 0.002
    cov_RCP_pos_old: 0.1
    cov_RCP_ort_old: 0.1
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.1 # standard deviation of process noise on position RCP
    std_sys_ort: 0.1 # standard deviation of process noise on orientation RCP
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]      
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]           
    n_iter: 1
    num_points_upd: 1000 # observation batch size