/**:
  ros__parameters:
    topic_imu: /vn100/imu
    acc_ratio: false  
    lidars: ["livox"]
    livox:
      topic_lidar: /livox/lidar 
      lidar_type: Mid70Avia
      scan_line: 1
      blind: 0.5
      q_lb: [0.00159994149920860,	0.999963437005377,	-9.99963437005377e-05,	-0.00839969287084516]        
      t_lb: [0.0111, -0.0089, 0.0372]  
      w_pt: 0.01
    lidar_time_offset: 0.0

    knot_hz: 100
    if_lidar_only: true
    
    ds_scan_voxel: 0.5
    point_filter_num: 2
    nn_thresh: 0.5
    coeff_cov: 2.0
    num_nn: 5

    ds_lm_voxel: 0.5
    cube_len: 2000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.1
    cov_RCP_ort_old: 0.1
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.1
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]       
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]      
    n_iter: 1    
    num_points_upd: 500
