/**:
  ros__parameters:
    topic_imu: /robot1/livox/imu
    acc_ratio: true 
    lidars: ["livox"]
    livox:
      topic_lidar: /robot1/livox/lidar 
      lidar_type: HAP360
      scan_line: 4
      blind: 0.5
      q_lb: [1.0, 0.0, 0.0, 0.0]        
      t_lb: [0.011, 0.02329, -0.04412]  
      w_pt: 0.01 
    lidar_time_offset: 0.0

    knot_hz: 100
    if_lidar_only: false
    
    ds_scan_voxel: 0.2
    point_filter_num: 1
    nn_thresh: 0.5
    coeff_cov: 5.0
    num_nn: 8

    ds_lm_voxel: 0.2
    cube_len: 1000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.5
    cov_RCP_ort_old: 0.5
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.1
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]     
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]       
    n_iter: 3   
    num_points_upd: 100
