/**:
  ros__parameters:
    topic_imu: /gt_box/livox/imu
    acc_ratio: true  
    lidars: ["hesai"]
    livox:
      topic_lidar: /gt_box/livox/lidar 
      lidar_type: Mid360Boxi
      scan_line: 4
      blind: 0.5
      q_lb: [0.999976, 0.000002, 0.000670, 0.006906]
      t_lb: [0.010345, 0.022305, -0.033211]
      w_pt: 0.01
    hesai:
      topic_lidar: /gt_box/hesai/points 
      lidar_type: Hesai
      scan_line: 32
      blind: 0.5
      q_lb: [0.000793920391926, -0.703743110426531, 0.710453977622183, -0.000387167175118]
      t_lb: [-0.016286160655580, -0.010352248240829, 0.128925315833111]
      w_pt: 0.01
    lidar_time_offset: 0.0

    knot_hz: 100
    if_lidar_only: true
    
    ds_scan_voxel: 0.2
    point_filter_num: 2
    nn_thresh: 0.5
    coeff_cov: 10.0
    num_nn: 5

    ds_lm_voxel: 0.2
    cube_len: 1000.0

    cov_P0: 0.02
    cov_RCP_pos_old: 0.5
    cov_RCP_ort_old: 0.5
    cov_RCP_pos_new: 1.0
    cov_RCP_ort_new: 1.0
    std_sys_pos: 0.1
    std_sys_ort: 0.1
    cov_acc: [1.0,1.0,1.0]
    cov_gyro: [0.1,0.1,0.1]      
    cov_ba: [0.2, 0.2, 0.2]
    cov_bg: [0.2, 0.2, 0.2]      
    n_iter: 1    
    num_points_upd: 300
